Repository pie-sfac/3-14-ketotop, pull requests merged in 2023-08, with the labels that each got.

#40 feat: Button 컴포넌트 기능구현 (#39)
  package.json
  src/lib/components/Button/.gitkeep
  src/lib/components/Button/Contained/index.tsx
  src/lib/components/Button/Contained/styles.ts
  src/lib/components/Button/Outline/index.tsx
  src/lib/components/Button/Outline/styles.ts
  src/lib/components/Button/index.ts
  src/lib/components/Button/type.ts
  tsconfig.json
  vite.config.ts
Labels: 🔮 Feature, 🎨 Design

#22 feat: Tabs 컴포넌트 기능 개발 (#20)
  src/lib/components/Tabs/.gitkeep
  src/lib/components/Tabs/TabComponent/index.tsx
  src/lib/components/Tabs/TabComponent/styles.ts
  src/lib/components/Tabs/TabComponent/type.ts
  src/lib/components/Tabs/index.tsx
  src/lib/components/Tabs/styles.ts
  src/lib/components/Tabs/type.ts
Labels: 🔮 Feature, 🎨 Design

#38 feat: Dropdown 구현 - 두가지 케이스 모두 구현 완료 (#33)
  src/lib/components/Dropdown/.gitkeep
  src/lib/components/Dropdown/General/index.tsx
  src/lib/components/Dropdown/General/styles.ts
  src/lib/components/Dropdown/General/type.ts
  src/lib/components/Dropdown/List/index.tsx
  src/lib/components/Dropdown/List/styles.ts
  src/lib/components/Dropdown/List/type.ts
  src/lib/components/Dropdown/index.ts
Labels: 🔮 Feature, 🎨 Design

#36 feat: Banner 컴포넌트 개발 (#15)
  src/lib/components/Banners/index.tsx
  src/lib/components/Banners/styles.ts
  src/lib/components/Banners/type.ts
Labels: 🔮 Feature, 🎨 Design

#42 feat: Component - AppBar 개발 (#37)
  src/lib/components/AppBar/index.tsx
  src/lib/components/AppBar/styles.ts
  src/lib/components/AppBar/type.ts
  src/lib/foundation/Icon/type.ts
Labels: 🔮 Feature, 🎨 Design

#23 feat: Dialog 컴포넌트 구현 (#19)
  src/lib/components/Dialog/.gitkeep
  src/lib/components/Dialog/index.tsx
  src/lib/components/Dialog/styles.ts
  src/lib/components/Dialog/type.ts
Labels: 🔮 Feature, 🎨 Design

#31 feat: TextField 컴포넌트 제작 (#24)
  src/lib/components/TextField/.gitkeep
  src/lib/components/TextField/index.tsx
  src/lib/components/TextField/style.ts
  src/lib/components/TextField/type.ts
Labels: 🔮 Feature, 🎨 Design

#16 feat: Snackbar컴포넌트 구현 - 코드수정했습니다 (#11)
  src/lib/components/SnackBar/.gitkeep
  src/lib/components/SnackBar/index.tsx
  src/lib/components/SnackBar/style.ts
  src/lib/components/SnackBar/type.ts
  src/lib/components/SnackBar/useSanckbar.ts
Labels: 🔮 Feature, 🎨 Design

#47 feat: Label 컴포넌트 기능 개발
  src/lib/components/Label/.gitkeep
  src/lib/components/Label/index.tsx
  src/lib/components/Label/styles.ts
  src/lib/components/Label/type.ts
Labels: 🔮 Feature

#51 refactor: Foundation - Icon 스타일 수정 (#46)
  src/lib/foundation/Icon/index.tsx
  src/lib/foundation/Icon/styles.ts
  src/lib/foundation/Icon/type.ts
Labels: 🛠 Refactor, ✨ Style

#55 refactor: Foundation -Layout 스타일 수정 (#45)
  src/lib/foundation/Layout/index.tsx
  src/lib/foundation/Layout/styles.ts
  src/lib/foundation/Layout/type.ts
Labels: 🐞 Bug Fix, 🛠 Refactor, ✨ Style

#59 refactor: Component - Dialog 버그 수정 및 리팩토링
  src/lib/components/Dialog/DialogButton/index.tsx
  src/lib/components/Dialog/DialogButton/styles.ts
  src/lib/components/Dialog/DialogButton/type.ts
  src/lib/components/Dialog/index.tsx
  src/lib/components/Dialog/styles.ts
  src/lib/components/Dialog/type.ts
Labels: 🐞 Bug Fix, 🛠 Refactor

#70 [bug & refactor] Component - TextField 버그 및 리팩토링 (#64)
  src/lib/components/TextField/index.tsx
  src/lib/components/TextField/style.ts
  src/lib/components/TextField/type.ts
Labels: 🐞 Bug Fix, 🛠 Refactor, 👀 Accessibility

#68 feat: Picker 의 캘린더부분 기능구현
  package.json
  src/lib/components/Picker/.gitkeep
  src/lib/components/Picker/Button/styles.ts
  src/lib/components/Picker/Calendar/index.tsx
  src/lib/components/Picker/Calendar/type.ts
  src/lib/components/Picker/Wrapper/styles.ts
  src/lib/components/Picker/index.ts
Labels: 🔮 Feature

#75 refactor: Component -Banner 버그 수정 및 리팩토링 (#74)
  src/lib/components/Banners/index.tsx
  src/lib/components/Banners/type.ts
  src/lib/components/Thumbnails/styles.ts
Labels: 🐞 Bug Fix, 🔮 Feature, 🛠 Refactor, ✨ Style

#73 refactor: Component -Thumbnails 버그 수정 및 리팩토링 (#69)
  src/lib/components/Thumbnails/Delete/index.tsx
  src/lib/components/Thumbnails/Image/index.tsx
  src/lib/components/Thumbnails/Video/index.tsx
  src/lib/components/Thumbnails/styles.ts
  src/lib/components/Thumbnails/type.ts
  src/lib/foundation/Icon/type.ts
Labels: 🐞 Bug Fix, 🔮 Feature, 🛠 Refactor, ✨ Style

#62 refactor: Foundation -SelectionControls 버그 수정 및 리팩토링 (#58)
  src/lib/foundation/SelectionControls/Input/index.tsx
  src/lib/foundation/SelectionControls/Label/index.tsx
  src/lib/foundation/SelectionControls/index.tsx
  src/lib/foundation/SelectionControls/styles.ts
  src/lib/foundation/SelectionControls/type.ts
Labels: 🐞 Bug Fix, 🔮 Feature, 🛠 Refactor, 🎨 Design, 👀 Accessibility

#76 refactor: Component -AppBar 버그 수정 및 모듈화(#63)
  src/lib/components/AppBar/Button/index.tsx
  src/lib/components/AppBar/Icon/index.tsx
  src/lib/components/AppBar/index.tsx
  src/lib/components/AppBar/styles.ts
  src/lib/components/AppBar/type.ts
  src/lib/foundation/Icon/styles.ts
  src/lib/foundation/Icon/type.ts
Labels: 🐞 Bug Fix, 🔮 Feature, 🛠 Refactor, ✨ Style

#61 refactor: 스낵바 컴포넌트 리팩토링 및 버그 수정
  src/lib/components/SnackBar/index.tsx
  src/lib/components/SnackBar/style.ts
Labels: 🐞 Bug Fix, 🛠 Refactor

#79 [fix & refactor] Component - Dropdown 누락된 disabled 기능 추가
  src/lib/components/Dropdown/General/index.tsx
  src/lib/components/Dropdown/General/styles.ts
  src/lib/components/Dropdown/General/type.ts
  src/lib/components/Dropdown/List/index.tsx
  src/lib/components/Dropdown/List/styles.ts
Labels: 🐞 Bug Fix, 🛠 Refactor, 🎨 Design

#81 refactor: Tabs 컴포넌트 버그 수정 및 리팩토링 작업
  src/lib/components/Tabs/TabComponent/index.tsx
  src/lib/components/Tabs/TabComponent/styles.ts
  src/lib/components/Tabs/TabComponent/type.ts
  src/lib/components/Tabs/index.tsx
  src/lib/components/Tabs/styles.ts
  src/lib/components/Tabs/type.ts
Labels: 🐞 Bug Fix, 🛠 Refactor, 👀 Accessibility

#82 refactor: Component - Navigation bar 버그 수정 및 모듈화(#77)
  src/lib/components/NavigationBar/Bottom/BottomItem/index.tsx
  src/lib/components/NavigationBar/Bottom/BottomItem/styles.ts
  src/lib/components/NavigationBar/Bottom/index.tsx
  src/lib/components/NavigationBar/Bottom/styles.ts
  src/lib/components/NavigationBar/Top/TopMenu/index.tsx
  src/lib/components/NavigationBar/Top/TopMenu/styles.ts
  src/lib/components/NavigationBar/Top/TopProfile/index.tsx
  src/lib/components/NavigationBar/Top/TopProfile/styles.ts
  src/lib/components/NavigationBar/Top/index.tsx
  src/lib/components/NavigationBar/Top/style.ts
  src/lib/components/NavigationBar/index.ts
  src/lib/components/NavigationBar/type.ts
  src/lib/components/index.ts
Labels: 🐞 Bug Fix, 🔮 Feature, 🛠 Refactor, ✨ Style

#84 feat: component - ButtonFAB 기능 구현
  package-lock.json
  src/lib/components/ButtonFAB/.gitkeep
  src/lib/components/ButtonFAB/Circle/index.tsx
  src/lib/components/ButtonFAB/Circle/styles.ts
  src/lib/components/ButtonFAB/Round/index.tsx
  src/lib/components/ButtonFAB/Round/styles.ts
  src/lib/components/ButtonFAB/index.tsx
  src/lib/components/ButtonFAB/type.ts
Labels: 🔮 Feature, 🛠 Refactor, 🎨 Design

#86 Feat : component - Time Picker
  package-lock.json
  package.json
  src/lib/components/Picker/Time/index.tsx
  src/lib/components/Picker/Time/styles.ts
  src/lib/components/Picker/Time/type.ts
  src/lib/components/Picker/index.ts
Labels: 🔮 Feature, 🎨 Design
