Repository pie-sfac/3-14-ketotop, pull requests merged in 2023-07, with the labels that each got.

#6 feat: layout 타입에 따른 사이즈 지정 (#2)
  src/lib/foundation/Layout/.gitkeep
  src/lib/foundation/Layout/index.tsx
  src/lib/foundation/Layout/styles.ts
  src/lib/foundation/Layout/type.ts
Labels: 🔮 Feature

#5 feat: Foundation Color 기능 구현 (#3)
  src/lib/foundation/Color/.gitkeep
  src/lib/foundation/Color/data/foundationColor.json
  src/lib/foundation/Color/index.ts
  src/lib/foundation/index.ts
Labels: 🔮 Feature

#9 feat: Typography시스템 구현 (#1)
  package-lock.json
  package.json
  src/lib/foundation/Typography/.gitkeep
  src/lib/foundation/Typography/FontFamily/Pretendard/css/pretendard.css
  src/lib/foundation/Typography/FontFamily/Pretendard/fonts/woff/Pretendard-Black.woff
  src/lib/foundation/Typography/FontFamily/Pretendard/fonts/woff/Pretendard-Bold.woff
  src/lib/foundation/Typography/FontFamily/Pretendard/fonts/woff/Pretendard-ExtraBold.woff
  src/lib/foundation/Typography/FontFamily/Pretendard/fonts/woff/Pretendard-ExtraLight.woff
  src/lib/foundation/Typography/FontFamily/Pretendard/fonts/woff/Pretendard-Light.woff
  src/lib/foundation/Typography/FontFamily/Pretendard/fonts/woff/Pretendard-Medium.woff
  src/lib/foundation/Typography/FontFamily/Pretendard/fonts/woff/Pretendard-Regular.woff
  src/lib/foundation/Typography/FontFamily/Pretendard/fonts/woff/Pretendard-SemiBold.woff
  src/lib/foundation/Typography/FontFamily/Pretendard/fonts/woff/Pretendard-Thin.woff
  src/lib/foundation/Typography/FontFamily/Pretendard/fonts/woff2/Pretendard-Black.woff2
  src/lib/foundation/Typography/FontFamily/Pretendard/fonts/woff2/Pretendard-Bold.woff2
  src/lib/foundation/Typography/FontFamily/Pretendard/fonts/woff2/Pretendard-ExtraBold.woff2
  src/lib/foundation/Typography/FontFamily/Pretendard/fonts/woff2/Pretendard-ExtraLight.woff2
  src/lib/foundation/Typography/FontFamily/Pretendard/fonts/woff2/Pretendard-Light.woff2
  src/lib/foundation/Typography/FontFamily/Pretendard/fonts/woff2/Pretendard-Medium.woff2
  src/lib/foundation/Typography/FontFamily/Pretendard/fonts/woff2/Pretendard-Regular.woff2
  src/lib/foundation/Typography/FontFamily/Pretendard/fonts/woff2/Pretendard-SemiBold.woff2
  src/lib/foundation/Typography/FontFamily/Pretendard/fonts/woff2/Pretendard-Thin.woff2
  src/lib/foundation/Typography/FontFamily/Roboto/css/roboto/roboto-fontface.css
  src/lib/foundation/Typography/FontFamily/Roboto/fonts/roboto/Roboto-Black.woff
  src/lib/foundation/Typography/FontFamily/Roboto/fonts/roboto/Roboto-Black.woff2
  src/lib/foundation/Typography/FontFamily/Roboto/fonts/roboto/Roboto-BlackItalic.woff
  src/lib/foundation/Typography/FontFamily/Roboto/fonts/roboto/Roboto-BlackItalic.woff2
  src/lib/foundation/Typography/FontFamily/Roboto/fonts/roboto/Roboto-Bold.woff
  src/lib/foundation/Typography/FontFamily/Roboto/fonts/roboto/Roboto-Bold.woff2
  src/lib/foundation/Typography/FontFamily/Roboto/fonts/roboto/Roboto-BoldItalic.woff
  src/lib/foundation/Typography/FontFamily/Roboto/fonts/roboto/Roboto-BoldItalic.woff2
  src/lib/foundation/Typography/FontFamily/Roboto/fonts/roboto/Roboto-Light.woff
  src/lib/foundation/Typography/FontFamily/Roboto/fonts/roboto/Roboto-Light.woff2
  src/lib/foundation/Typography/FontFamily/Roboto/fonts/roboto/Roboto-LightItalic.woff
  src/lib/foundation/Typography/FontFamily/Roboto/fonts/roboto/Roboto-LightItalic.woff2
  src/lib/foundation/Typography/FontFamily/Roboto/fonts/roboto/Roboto-Medium.woff
  src/lib/foundation/Typography/FontFamily/Roboto/fonts/roboto/Roboto-Medium.woff2
  src/lib/foundation/Typography/FontFamily/Roboto/fonts/roboto/Roboto-MediumItalic.woff
  src/lib/foundation/Typography/FontFamily/Roboto/fonts/roboto/Roboto-MediumItalic.woff2
  src/lib/foundation/Typography/FontFamily/Roboto/fonts/roboto/Roboto-Regular.woff
  src/lib/foundation/Typography/FontFamily/Roboto/fonts/roboto/Roboto-Regular.woff2
  src/lib/foundation/Typography/FontFamily/Roboto/fonts/roboto/Roboto-RegularItalic.woff
  src/lib/foundation/Typography/FontFamily/Roboto/fonts/roboto/Roboto-RegularItalic.woff2
  src/lib/foundation/Typography/FontFamily/Roboto/fonts/roboto/Roboto-Thin.woff
  src/lib/foundation/Typography/FontFamily/Roboto/fonts/roboto/Roboto-Thin.woff2
  src/lib/foundation/Typography/FontFamily/Roboto/fonts/roboto/Roboto-ThinItalic.woff
  src/lib/foundation/Typography/FontFamily/Roboto/fonts/roboto/Roboto-ThinItalic.woff2
  src/lib/foundation/Typography/FontFamily/font.css
  src/lib/foundation/Typography/Style/typoStyle.ts
  src/lib/foundation/Typography/index.ts
Labels: 🔮 Feature

#17 feat: 아이콘 컴포넌트 (#7)
  public/assets/Icon/add.svg
  public/assets/Icon/appbar_center.svg
  public/assets/Icon/appbar_center_gray.svg
  public/assets/Icon/appbar_home.svg
  public/assets/Icon/appbar_home_gray.svg
  public/assets/Icon/appbar_mypage.svg
  public/assets/Icon/appbar_mypage_gray.svg
  public/assets/Icon/appbar_patient.svg
  public/assets/Icon/appbar_patient_gray.svg
  public/assets/Icon/appbar_reserve.svg
  public/assets/Icon/appbar_reserve_gray.svg
  public/assets/Icon/arrow_more.svg
  public/assets/Icon/back.svg
  public/assets/Icon/back_small.svg
  public/assets/Icon/bin.svg
  public/assets/Icon/calendar.svg
  public/assets/Icon/centerinfo.svg
  public/assets/Icon/close.svg
  public/assets/Icon/comment.svg
  public/assets/Icon/delete.svg
  public/assets/Icon/delete_small.svg
  public/assets/Icon/deletecircle_gray.svg
  public/assets/Icon/document.svg
  public/assets/Icon/down.svg
  public/assets/Icon/drop_less.svg
  public/assets/Icon/drop_more.svg
  public/assets/Icon/edit.svg
  public/assets/Icon/filter.svg
  public/assets/Icon/half_star.svg
  public/assets/Icon/help.svg
  public/assets/Icon/less_small.svg
  public/assets/Icon/message.svg
  public/assets/Icon/more_small.svg
  public/assets/Icon/more_vert.svg
  public/assets/Icon/next_small.svg
  public/assets/Icon/notice.svg
  public/assets/Icon/playcircle.svg
  public/assets/Icon/redo.svg
  public/assets/Icon/reset.svg
  public/assets/Icon/search.svg
  public/assets/Icon/settings.svg
  public/assets/Icon/star_off.svg
  public/assets/Icon/star_on.svg
  public/assets/Icon/thumbnails_checkcircle.svg
  public/assets/Icon/thumbnails_deletecircle.svg
  public/assets/Icon/thumbnails_playcircle.svg
  public/assets/Icon/time.svg
  public/assets/Icon/undo.svg
  public/assets/Icon/up.svg
  public/assets/Icon/videocam_gray.svg
  public/assets/Icon/videoform.svg
  public/assets/Icon/visibility.svg
  public/assets/Icon/visibility_off.svg
  public/assets/Icon/visibility_on.svg
  src/lib/foundation/Icon/.gitkeep
  src/lib/foundation/Icon/index.tsx
  src/lib/foundation/Icon/type.ts
Labels: 🔮 Feature, ✨ Style

#14 feat: 컴포넌트를 통한 체크박스/라디오 상태 설정 (#13)
  src/lib/foundation/SelectionControls/.gitkeep
  src/lib/foundation/SelectionControls/index.tsx
  src/lib/foundation/SelectionControls/styles.ts
  src/lib/foundation/SelectionControls/type.ts
Labels: 🔮 Feature, 🎨 Design

#18 feat: PopupMenu 컴포넌트 기능개발 (#10)
  src/lib/components/PopupMenu/.gitkeep
  src/lib/components/PopupMenu/PopupMenuList/index.tsx
  src/lib/components/PopupMenu/PopupMenuList/styles.ts
  src/lib/components/PopupMenu/PopupMenuList/type.ts
  src/lib/components/PopupMenu/index.tsx
  src/lib/components/PopupMenu/styles.ts
  src/lib/components/PopupMenu/type.ts
Labels: 🔮 Feature

#28 feat: shadowBox 값 GlobalStyle 추가 (#12)
  src/App.tsx
  src/lib/foundation/Shadow/.gitkeep
  src/lib/foundation/Shadow/styled.ts
  src/styles/GlobalStyle.ts
Labels: 🔮 Feature, 🎨 Design

#34 feat: NavigationBar 컴포넌트 개발 (#32)
  src/lib/components/NavigationBar/Bottom/index.tsx
  src/lib/components/NavigationBar/Bottom/style.ts
  src/lib/components/NavigationBar/Top/index.tsx
  src/lib/components/NavigationBar/Top/style.ts
  src/lib/components/NavigationBar/index.ts
  src/lib/components/NavigationBar/type.ts
Labels: 🔮 Feature, 🎨 Design

#30 feat: Thumbnails 컴포넌트 개발 (#21)
  src/lib/components/Thumbnails/Image/index.tsx
  src/lib/components/Thumbnails/Video/index.tsx
  src/lib/components/Thumbnails/index.tsx
  src/lib/components/Thumbnails/styles.ts
  src/lib/components/Thumbnails/type.ts
Labels: 🔮 Feature, 🎨 Design
